name: Database Migrations

on:
  push:
    branches:
      - terraform
    paths:
      - 'migration/**'

jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      PGHOST: ${{ secrets.PGHOST }}
      PGPORT: ${{ secrets.PGPORT }}
      PGUSER: ${{ secrets.PGUSER }}
      PGPASSWORD: ${{ secrets.PGPASSWORD }}
      PGDATABASE: ${{ secrets.PGDATABASE }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install PostgreSQL client
        run: sudo apt-get install -y postgresql-client

      - name: Ensure schema_migrations table exists
        run: |
          psql -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE" -c "
            CREATE TABLE IF NOT EXISTS schema_migrations (
              filename TEXT PRIMARY KEY,
              applied_at TIMESTAMPTZ DEFAULT now()
            );"

      - name: Run migration files recursively
        run: |
          set -e
          for file in $(find migration -type f -name '*.sql' | sort); do
            filename=$(basename "$file")
            echo "Checking migration: $filename"
            applied=$(psql -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE" -tAc \
              "SELECT 1 FROM schema_migrations WHERE filename = '$filename'")
            if [ "$applied" != "1" ]; then
              echo "Applying migration $filename"
              psql -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE" -f "$file"
              psql -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE" -c \
                "INSERT INTO schema_migrations (filename) VALUES ('$filename');"
            else
              echo "Skipping $filename (already applied)"
            fi
          done
