name: Deploy Backend to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_API_HOST }} << 'EOF'
          set -e

          sudo chown -R ubuntu:ubuntu /home/ubuntu/bulk-logistics

          cd /home/ubuntu/bulk-logistics
          git config --global --add safe.directory /home/ubuntu/bulk-logistics
          git fetch --all
          git reset --hard origin/main
          git clean -fd

          cd backend
          npm install
          npm run build
          pm2 restart bulk-logistics-backend || pm2 start dist/app.js --name bulk-logistics-backend
          EOF
