name: Test Frontend Build

on:
  pull_request:
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: |
          npm ci

      - name: Run tests
        working-directory: frontend
        run: |
          npm run test

      # - name: Build project
      #   working-directory: frontend
      #   run: |
      #     npm run build
          
      # - name: Verify build output
      #   working-directory: frontend
      #   run: |
      #     if [ ! -d "dist" ]; then
      #       echo "Build directory 'dist' not found!"
      #       exit 1
      #     fi
          
      #     # Check for essential build files
      #     required_files=(
      #       "dist/index.html"
      #       "dist/assets"
      #     )
          
      #     for file in "${required_files[@]}"; do
      #       if [ ! -e "$file" ]; then
      #         echo "Required build output not found: $file"
      #         exit 1
      #       fi
      #     done